### ISSUE TITLE
TypeError: __init__() takes at most 6 arguments (7 given)

### ISSUE THREAD

**Issue by rshravan** [buriburisuri/speech-to-text-wavenet#1]
Hi, 
Might be a small issue, but I cannot get pass this. This is the error log (while executing python recognize.py --file p225_001.wav )

Traceback (most recent call last):
  File "recognize.py", line 27, in <module>
    data = VCTK()
  File "/Users/rs/Documents/in/Work/Development/speech-to-text-wavenet-master/data.py", line 54, in __init__
    capacity=128, num_threads=32)
  File "//anaconda/lib/python2.7/site-packages/sugartensor/sg_queue.py", line 49, in wrapper
    runner = FuncQueueRunner(enqueue_func, queue, [enqueue_op] * opt.num_threads)
  File "//anaconda/lib/python2.7/site-packages/sugartensor/sg_queue.py", line 69, in __init__
    queue_closed_exception_types, queue_runner_def)
TypeError: __init__() takes at most 6 arguments (7 given)

Would be great if you can help me out!

**Comment by pannous** [comment]
`python -c "import tensorflow; print tensorflow.__version__"`
should be 0.11.0

**Comment by rshravan** [comment]
Thanks a ton! That resolves the issue! :) 
Recognition speed is very good. I ran it against Google's WaveNet generated voice https://storage.googleapis.com/deepmind-media/pixie/us-english/parametric-1.wav and it recognized "phe blide a got an anin ide it mero in romavd an i vinger of lilnd the rekerd by ran of qliter". I think it's a matter of further training and increasing the vocab base. Excellent work!

**Comment by buriburisuri** [comment]
@rshravan  Thank you.  I omitted the data augmentation and I think that is the main cause of the poor result because  WaveNet generated voice sounds somewhat noisy.  I guess that WaveNet  TTS can be used as another source of augmentation.  Thank you for your inspiration.
