### ISSUE TITLE
Upgrade to sugartensor 0.0.2.0

### ISSUE THREAD

**Issue by samuelleach** [buriburisuri/speech-to-text-wavenet#15]
Thanks for making this project!

I found that I needed to use the version of sugartensor 0.0.1.9.

Using 0.0.2.0 I get the following error when running `recognize.py`

```
INFO:tensorflow:1202:21:10:24.229:data.py:60] VCTK corpus loaded.(total data=36395, total batch=2274)
Traceback (most recent call last):
  File "recognize.py", line 62, in <module>
    z = x.sg_conv1d(size=1, dim=num_dim, act='tanh', bn=True)
  File "/Users/-------/anaconda3/envs/py27/lib/python2.7/site-packages/sugartensor/sg_main.py", line 147, in wrapper
    for t in tf.global_variables():
AttributeError: 'module' object has no attribute 'global_variables'
```

**Comment by buriburisuri** [comment]
Yes, 0.0.2.0 requires tensorflow 0.12rc.

**Comment by nao0811ta** [comment]
same problem.. 
I can't upgrade to tensorflow 0.12rc because of using cuda 7.5 on ec2 instance g2.2xlarge.

**Comment by nao0811ta** [comment]
I'm sorry. I solved by downgrade to sugartensor 0.0.1.9

**Comment by Spiritdude** [comment]
+1
```
pip uninstall sugartensor
pip install -Iv sugartensor==0.0.1.9
```

**Comment by aryachiranjeev** [comment]
i am using tensorflow version - 1.12.0
and python-3.5.2
and i am using sugartensor -0.0.1.9 but i am getting error AttributeError: module 'tensorflow' has no attribute 'core'
 on importing sugartensor
so which sugartensor version should i use

**Comment by alison0303** [comment]
i am using tensorflow-2.0.0 and python-3.6.5, i haven't have of your problems but actually i also met some troubles on the code, my path of the LJSPeech is always wrong. What should&nbsp; i do



---Original---
