### ISSUE TITLE
Can I train it to use other languages? 

### ISSUE THREAD

**Issue by steve21124** [buriburisuri/speech-to-text-wavenet#2]
if it is, what will be the steps?

**Comment by rshravan** [comment]
Yes, the model is language independent.

**Comment by buriburisuri** [comment]
Yes, language independent. You need sentence pairs of wave and text files. Please see VCTK corpus file structure and data.py file to identify how you can handle these.  It'll not be difficult.

**Comment by steve21124** [comment]
thanks

**Comment by ramaseshan** [comment]
I am trying to apply this for Hindi (Indian Language). The following is the character set to english keyboard mapping. http://www.lexilogos.com/keyboard/devanagari.htm 

So my data.py do I update all these characters  ?

**Comment by ramaseshan** [comment]
When I try to define characters of other languages and in the train step, I get this error

InvalidArgumentError (see above for traceback): Assign requires shapes of both tensors to match. lhs shape= [1,128,43] rhs shape= [1,128,28]

I looked at the VCTK corpus and setup my audio/translation files. Modified data.py to include new characters. What else am I missing.
