### ISSUE TITLE
recognize.py --> AttributeError: 'SparseTensor' object has no attribute 'shape'

### ISSUE THREAD

**Issue by a00achild1** [buriburisuri/speech-to-text-wavenet#21]
Hi,
I was trying the performance of the pre-trained model.
When I run  `python recognize.py --file asset/data/wav48/p225/p225_003.wav`
I got the following error:

> Traceback (most recent call last):
  File "recognize.py", line 80, in <module>
    y = tf.sparse_to_dense(decoded[0].indices, decoded[0].shape, decoded[0].values) + 1
AttributeError: 'SparseTensor' object has no attribute 'shape'

But I am sure that SparseTensor has the attribute 'shape'
Did i miss something?
Any help will be appreciated!

**Comment by a00achild1** [comment]
btw, I change the code to below:
`y = tf.sparse_to_dense(decoded[0].indices, decoded[0].get_shape()[1], decoded[0].values) + 1`
and got this error:

> File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/constant_op.py", line 212, in _dimension_tensor_conversion_function
    raise ValueError("Cannot convert an unknown Dimension to a Tensor: %s" % d)
ValueError: Cannot convert an unknown Dimension to a Tensor: ?

and then I found that the shape of the decoded[0] is (?, ?)
Did anyone has the same issue?

**Comment by a00achild1** [comment]
I change
`y = tf.sparse_to_dense(decoded[0].indices, decoded[0].get_shape()[1], decoded[0].values) + 1`
to
`y = tf.sparse_tensor_to_dense(decoded[0])`
and pass

**Comment by buriburisuri** [comment]
@a00achild1  Sorry for late reply. ( enjoyed long holidays ). Thank you for your information.  I'll check this.
