### ISSUE TITLE
Error: speaker_info.txt missing

### ISSUE THREAD

**Issue by bluemoon9** [buriburisuri/speech-to-text-wavenet#29]
Hi, I'm a beginner to Machine Learning concepts and I'm just trying to run the code. I have downloaded your pre-trained model (Extracted it to 'asset/train/ckpt/' as suggested) and  I'm trying to run 'recognize.py' but I keep getting this error. I have not downloaded the VCTK dataset as I thought since I already have the pre-trained model, I don't need to download the dataset and train the model. Is my way of thinking correct or do I need to definitely download the VCTK dataset , extract it in 'asset/data/'  and then run 'recognize.py'?

Thank you.

**Comment by jeremyblalock** [comment]
This is because you did not download the dataset first @bluemoon9. Even when using the pre-trained models, you still will need to download & extract the dataset as described in the README.

**Comment by jeremyblalock** [comment]
As a general note, I think it would be perhaps a good idea to remove the dependency of `speakers-info.txt` from `recognize.py`, if others agree. From what I can tell, `speaker-info.txt` is not actually used in . It looks like it is simply required by `data.py` which is used to load the pretrained models' save points.

But for now, downloading the dataset will make everything work as expected.

**Comment by bluemoon9** [comment]
Thank you @jeremyblalock

**Comment by buriburisuri** [comment]
@jeremyblalock  Thank you !!!

**Comment by martsen** [comment]
@jeremyblalock it will be good solution to remove speaker-info.txt from data.py dependencies.
