### ISSUE TITLE
 No module named tensorboard.plugins

### ISSUE THREAD

**Issue by bloodcarter** [buriburisuri/speech-to-text-wavenet#34]
Any thoughts?

```
[ec2-user@ip-172-31-43-155 speech-to-text-wavenet]$ python recognize.py --file .                                                               /test.wav
I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library                                                                libcublas.so.7.5 locally
I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library                                                                libcudnn.so.5 locally
I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library                                                                libcufft.so.7.5 locally
I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library                                                                libcuda.so.1 locally
I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library                                                                libcurand.so.7.5 locally
Traceback (most recent call last):
  File "recognize.py", line 2, in <module>
    import sugartensor as tf
  File "/usr/lib/python2.7/dist-packages/sugartensor/__init__.py", line 7, in <m                                                               odule>
    from .sg_train import *
  File "/usr/lib/python2.7/dist-packages/sugartensor/sg_train.py", line 9, in <m                                                               odule>
    from tensorflow.contrib.tensorboard.plugins import projector
ImportError: No module named tensorboard.plugins

```

**Comment by alivcor** [comment]
For anyone who gets this issue, upgrade your TensorFlow version to at least 1.0.0 (I had 0.10 on Python 2.7)

That solved my problem. Hope this helps someone 👍

**Comment by ashimiblessing** [comment]
Thanks for the tip alivcor, worked for me too.

**Comment by aiporre** [comment]
Great me too! :) I had a similar problem while importing the keras

**Comment by tharuniitk** [comment]
Doesn't it work still with tensorflow 0.10, python 2.7, the reason is that tensorflow 1.0 requires cuda 8.0 but on my server cuda 7.5 is installed and I cannot change it as I am not in sudoer's list and it may affect other users...Kindly help!!!

**Comment by alivcor** [comment]
@tharuniitk Install everything locally within your user directory. Not sure about the issue you're facing.

Request you to provide a log.

**Comment by tharuniitk** [comment]
Hi @alivcor Yes, I am installing everything like keras, tensorflow locally i.e. within a virtual environment, but the tensorflow 0.10 and below versions do work when you have cuda 8.0 installed in the system..An error of installing tensorflow 0.10 and importing keras with that version of tensorflow is attached in first pic. Then I uninstalled tensorflow 0.10 and installed the most recent version of tensorflow through pip and then i tried to import keras with tensorflow the error log is in second picture. Hope this clarifies my problem a bit..
![Uploading tensorflow_keras_Error.png…](picture1)
![Uploading error2_most_recent_isntallation_tensorflow.png…](picture2)
