### ISSUE TITLE
Training on own data -- ValueError

### ISSUE THREAD

**Issue by lightnarcissus** [buriburisuri/speech-to-text-wavenet#37]
Since I couldn't find any specific notes on training on your own corpus, I assumed it'd maintain the same structure as VCTK (asset/data/) with text description in (asset/data/txt/) and audio files to be trained in (asset/data/wav48/). 
Despite doing that I end up getting the following error trace:
`Traceback (most recent call last):
  File "train.py", line 26, in <module>
    data = VCTK(batch_size=batch_size)
  File "/Users/anshpatel/Downloads/speech-to-text-wavenet-master/data.py", line 45, in __init__
    labels, wave_files = self._load_corpus(data_path)
  File "/Users/anshpatel/Downloads/speech-to-text-wavenet-master/data.py", line 111, in _load_corpus
    self.max_len = np.max([len(s) for s in sents])
  File "/Users/anshpatel/anaconda/lib/python2.7/site-packages/numpy/core/fromnumeric.py", line 2252, in amax
    out=out, **kwargs)
  File "/Users/anshpatel/anaconda/lib/python2.7/site-packages/numpy/core/_methods.py", line 26, in _amax
    return umr_maximum(a, axis, None, out, keepdims)
ValueError: zero-size array to reduction operation maximum which has no identity`

Any idea on what is causing such an error?

**Comment by dzad** [comment]
same here

**Comment by ghost** [comment]
I am receiving the same error , did you get a solution to this?

**Comment by lightnarcissus** [comment]
@ParulSharma5 I am no longer getting the error. Making sure my SugarTensor and Tensorflow version matched those in the requirements and I had put the VCTK-Corpus properly in asset/data removed this error for me.

**Comment by ghost** [comment]
Thanks changing the location for  wav48 and txt directories under asset/data from asset/data/VCTK-Corpus did the trick.

**Comment by Hitesh95** [comment]
can u please tell me @ParulSharma5 how to train ur own data?
