### ISSUE TITLE
train.py ERROR

### ISSUE THREAD

**Issue by sidh104** [buriburisuri/speech-to-text-wavenet#42]
after running python3 train.py
am getting like this

Traceback (most recent call last):
  File "train.py", line 3, in <module>
    from data import VCTK
  File "/home/user/Desktop/Project/speech-to-text-wavenet-master/data.py", line 142
    print str_
             ^
SyntaxError: Missing parentheses in call to 'print'

Need a follow up regarding this.....

**Comment by gvoysey** [comment]
@sidh104 : it appears to me that this code is python2 only.

**Comment by sidh104** [comment]
thank u @gvoysey  rectified
