### ISSUE TITLE
TypeError: reduce_sum() got an unexpected keyword argument 'axis'

### ISSUE THREAD

**Issue by sidh104** [buriburisuri/speech-to-text-wavenet#48]
root@ubuntu:/home/user/Desktop/speech-to-text-wavenet-master# python train.py 
INFO:tensorflow:0303:01:36:26.310:data.py:73] VCTK corpus loaded.(total data=36395, total batch=2274)
Traceback (most recent call last):
  File "train.py", line 35, in <module>
    seq_len = tf.not_equal(x.sg_sum(dims=2), 0.).sg_int().sg_sum(dims=1)
  File "/usr/local/lib/python2.7/dist-packages/sugartensor/sg_main.py", line 151, in wrapper
    out = func(tensor, tf.sg_opt(kwargs))
  File "/usr/local/lib/python2.7/dist-packages/sugartensor/sg_transform.py", line 300, in sg_sum
    return tf.reduce_sum(tensor, axis=opt.axis, keep_dims=opt.keep_dims, name=opt.name)
TypeError: reduce_sum() got an unexpected keyword argument 'axis'

what is this error actually and what do i need to do exactly get rid and execute python train.py without any error

**Comment by sidh104** [comment]
got the fix!!!

If Dependencies are installed as described then it works.
Seems to brake with newer dependencies installed.
Used: pip freeze to see which version installed.
If a newer version is installed then uninstall: sudo pip uninstall sugartensor
Then install correct version: sudo pip install sugartensor==0.0.1.9
To install correct version of tensorflow: sudo pip install https://storage.googleapis.com/tensorflow/linux/cpu/tensorflow-0.11.0-cp27-none-linux_x86_64.whl

**Comment by EN10** [comment]
again, this is my comment a ref would be nice? @sidh104
https://github.com/buriburisuri/speech-to-text-wavenet/issues/49#issue-212079042
