### ISSUE TITLE
Train error: No valid path found.

### ISSUE THREAD

**Issue by rachel-bousfield** [buriburisuri/speech-to-text-wavenet#74]
I'm unable to train my model and keep getting the following errors interspersed as train.py executes. Has anyone else had this issue?

> I 0523:09:40:09.238:data.py:146] TRAIN set loaded.(total data=826, total batch=51)
I 0523:09:42:13.169:sg_train.py:327] Training started from epoch[000]-step[0].
train:   0%|                                    | 0/51 [00:00<?, ?b/s]2017-05-23 09:42:38.002544: W tensorflow/core/util/ctc/ctc_loss_calculator.cc:144] No valid path found.
train:   8%|██▏                         | 4/51 [00:30<06:35,  8.41s/b]2017-05-23 09:42:58.008032: W tensorflow/core/util/ctc/ctc_loss_calculator.cc:144] No valid path found.
2017-05-23 09:42:58.008057: W tensorflow/core/util/ctc/ctc_loss_calculator.cc:144] No valid path found.
train:  18%|████▉                       | 9/51 [00:58<04:40,  6.69s/b]2017-05-23 09:43:26.258079: W tensorflow/core/util/ctc/ctc_loss_calculator.cc:144] No valid path found.
train:  43%|███████████▋               | 22/51 [01:47<01:54,  3.94s/b]2017-05-23 09:44:16.270652: W tensorflow/core/util/ctc/ctc_loss_calculator.cc:144] No valid path found.
2017-05-23 09:44:16.848735: W tensorflow/core/util/ctc/ctc_loss_calculator.cc:144] No valid path found.
train:  45%|████████████▏              | 23/51 [01:57<02:35,  5.55s/b]2017-05-23 09:44:24.783569: W tensorflow/core/util/ctc/ctc_loss_calculator.cc:144] No valid path found.
train:  47%|████████████▋              | 24/51 [02:00<02:12,  4.92s/b]I 0523:09:44:26.987:sg_train.py:301] 	Epoch[000:gs=24] - loss =      inf
                                                                      I 0523:09:44:26.988:sg_train.py:301] ████Epoch[001:gs=24] - loss =      inf4/51 [00:00<?, ?b/s]
                                                                      I 0523:09:44:26.988:sg_train.py:301]     Epoch[002:gs=24] - loss =      inf
train:  47%|████████████████▍                  | 24/51 [00:00<?, ?b/s]I 0523:09:44:26.989:sg_train.py:301] 	Epoch[003:gs=24] - loss =      inf
                                                                      I 0523:09:44:26.990:sg_train.py:301] ████Epoch[004:gs=24] - loss =      inf4/51 [00:00<?, ?b/s]
                                                                      I 0523:09:44:26.991:sg_train.py:301]     Epoch[005:gs=24] - loss =      inf
train:  47%|████████████████▍                  | 24/51 [00:00<?, ?b/s]I 0523:09:44:26.991:sg_train.py:301] 	Epoch[006:gs=24] - loss =      inf
                                                                      I 0523:09:44:26.992:sg_train.py:301] ████Epoch[007:gs=24] - loss =      inf4/51 [00:00<?, ?b/s]
                                                                      I 0523:09:44:26.993:sg_train.py:301]     Epoch[008:gs=24] - loss =      inf
train:  47%|████████████████▍                  | 24/51 [00:00<?, ?b/s]I 0523:09:44:26.993:sg_train.py:301] 	Epoch[009:gs=24] - loss =      inf
                                                                      I 0523:09:44:26.994:sg_train.py:301] ████Epoch[010:gs=24] - loss =      inf4/51 [00:00<?, ?b/s]
                                                                      I 0523:09:44:26.995:sg_train.py:301]     Epoch[011:gs=24] - loss =      inf
train:  47%|████████████████▍                  | 24/51 [00:00<?, ?b/s]I 0523:09:44:26.995:sg_train.py:301] 	Epoch[012:gs=24] - loss =      inf
                                                                      I 0523:09:44:26.996:sg_train.py:301] ████Epoch[013:gs=24] - loss =      inf4/51 [00:00<?, ?b/s]
                                                                      I 0523:09:44:26.997:sg_train.py:301]     Epoch[014:gs=24] - loss =      inf
train:  47%|████████████████▍                  | 24/51 [00:00<?, ?b/s]I 0523:09:44:26.997:sg_train.py:301] 	Epoch[015:gs=24] - loss =      inf
                                                                      I 0523:09:44:26.998:sg_train.py:301] ████Epoch[016:gs=24] - loss =      inf4/51 [00:00<?, ?b/s]
                                                                      I 0523:09:44:26.999:sg_train.py:301]     Epoch[017:gs=24] - loss =      inf
train:  47%|████████████████▍                  | 24/51 [00:00<?, ?b/s]I 0523:09:44:26.999:sg_train.py:301] 	Epoch[018:gs=24] - loss =      inf
                                                                      I 0523:09:44:27.000:sg_train.py:301] ████Epoch[019:gs=24] - loss =      inf4/51 [00:00<?, ?b/s]
                                                                      I 0523:09:44:27.001:sg_train.py:301]     Epoch[020:gs=24] - loss =      inf
train:  47%|████████████████▍                  | 24/51 [00:00<?, ?b/s]I 0523:09:44:27.001:sg_train.py:301] 	Epoch[021:gs=24] - loss =      inf
                                                                      I 0523:09:44:27.002:sg_train.py:301] ████Epoch[022:gs=24] - loss =      inf4/51 [00:00<?, ?b/s]
                                                                      I 0523:09:44:27.003:sg_train.py:301]     Epoch[023:gs=24] - loss =      inf
train:  47%|████████████████▍                  | 24/51 [00:00<?, ?b/s]I 0523:09:44:27.003:sg_train.py:301] 	Epoch[024:gs=24] - loss =      inf
                                                                      I 0523:09:44:27.004:sg_train.py:301] ████Epoch[025:gs=24] - loss =      inf4/51 [00:00<?, ?b/s]
                                                                      I 0523:09:44:27.005:sg_train.py:301]     Epoch[026:gs=24] - loss =      inf
train:  47%|████████████████▍                  | 24/51 [00:00<?, ?b/s]I 0523:09:44:27.005:sg_train.py:301] 	Epoch[027:gs=24] - loss =      inf
                                                                      I 0523:09:44:27.006:sg_train.py:301] ████Epoch[028:gs=24] - loss =      inf4/51 [00:00<?, ?b/s]
                                                                      I 0523:09:44:27.007:sg_train.py:301]     Epoch[029:gs=24] - loss =      inf
train:  47%|████████████████▍                  | 24/51 [00:00<?, ?b/s]I 0523:09:44:27.007:sg_train.py:301] 	Epoch[030:gs=24] - loss =      inf
                                                                      I 0523:09:44:27.008:sg_train.py:301] ████Epoch[031:gs=24] - loss =      inf4/51 [00:00<?, ?b/s]
                                                                      I 0523:09:44:27.009:sg_train.py:301]     Epoch[032:gs=24] - loss =      inf
train:  47%|████████████████▍                  | 24/51 [00:00<?, ?b/s]I 0523:09:44:27.010:sg_train.py:301] 	Epoch[033:gs=24] - loss =      inf
                                                                      I 0523:09:44:27.010:sg_train.py:301] ████Epoch[034:gs=24] - loss =      inf4/51 [00:00<?, ?b/s]
                                                                      I 0523:09:44:27.011:sg_train.py:301]     Epoch[035:gs=24] - loss =      inf
train:  47%|████████████████▍                  | 24/51 [00:00<?, ?b/s]I 0523:09:44:27.012:sg_train.py:301] 	Epoch[036:gs=24] - loss =      inf
                                                                      I 0523:09:44:27.012:sg_train.py:301] ████Epoch[037:gs=24] - loss =      inf4/51 [00:00<?, ?b/s]
                                                                      I 0523:09:44:27.013:sg_train.py:301]     Epoch[038:gs=24] - loss =      inf
train:  47%|████████████████▍                  | 24/51 [00:00<?, ?b/s]I 0523:09:44:27.014:sg_train.py:301] 	Epoch[039:gs=24] - loss =      inf
                                                                      I 0523:09:44:27.014:sg_train.py:301] ████Epoch[040:gs=24] - loss =      inf4/51 [00:00<?, ?b/s]
                                                                      I 0523:09:44:27.015:sg_train.py:301]     Epoch[041:gs=24] - loss =      inf
train:  47%|████████████████▍                  | 24/51 [00:00<?, ?b/s]I 0523:09:44:27.016:sg_train.py:301] 	Epoch[042:gs=24] - loss =      inf
                                                                      I 0523:09:44:27.017:sg_train.py:301] ████Epoch[043:gs=24] - loss =      inf4/51 [00:00<?, ?b/s]
                                                                      I 0523:09:44:27.017:sg_train.py:301]     Epoch[044:gs=24] - loss =      inf
train:  47%|████████████████▍                  | 24/51 [00:00<?, ?b/s]I 0523:09:44:27.018:sg_train.py:301] 	Epoch[045:gs=24] - loss =      inf
                                                                      I 0523:09:44:27.019:sg_train.py:301] ████Epoch[046:gs=24] - loss =      inf4/51 [00:00<?, ?b/s]
                                                                      I 0523:09:44:27.019:sg_train.py:301]     Epoch[047:gs=24] - loss =      inf
train:  47%|████████████████▍                  | 24/51 [00:00<?, ?b/s]I 0523:09:44:27.020:sg_train.py:301] 	Epoch[048:gs=24] - loss =      inf
                                                                      I 0523:09:44:27.021:sg_train.py:301] ████Epoch[049:gs=24] - loss =      inf4/51 [00:00<?, ?b/s]
                                                                      I 0523:09:44:27.021:sg_train.py:301]     Epoch[050:gs=24] - loss =      inf
I 0523:09:44:52.963:sg_train.py:368] Training finished at epoch[50]-step[24].
Traceback (most recent call last):
  File "train.py", line 49, in <module>
    ep_size=data.num_batch, max_ep=50)         | 24/51 [00:00<?, ?b/s]
  File "/usr/local/lib/python2.7/site-packages/sugartensor/sg_train.py", line 69, in sg_train
    train_func(**opt)
  File "/usr/local/lib/python2.7/site-packages/sugartensor/sg_train.py", line 371, in wrapper
    (ep - 1, sess.run(tf.sg_global_step())))
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/contextlib.py", line 24, in __exit__           | 24/51 [00:00<?, ?b/s]
    self.gen.next()
  File "/usr/local/lib/python2.7/site-packages/tensorflow/python/training/supervisor.py", line 960, in managed_session█████▍                  | 24/51 [00:00<?, ?b/s]
    self.stop(close_summary_writer=close_summary_writer)
  File "/usr/local/lib/python2.7/site-packages/tensorflow/python/training/supervisor.py", line 788, in stop████████████████▍                  | 24/51 [00:00<?, ?b/s]
    stop_grace_period_secs=self._stop_grace_secs)
  File "/usr/local/lib/python2.7/site-packages/tensorflow/python/training/coordinator.py", line 389, in join███████████████▍                  | 24/51 [00:00<?, ?b/s]
    six.reraise(*self._exc_info_to_raise)
  File "/usr/local/lib/python2.7/site-packages/tensorflow/python/training/coordinator.py", line 296, in stop_on_exception██▍                  | 24/51 [00:00<?, ?b/s]
    yield
  File "/usr/local/lib/python2.7/site-packages/tensorflow/python/training/coordinator.py", line 494, in run████████████████▍                  | 24/51 [00:00<?, ?b/s]
    self.run_loop()
  File "/usr/local/lib/python2.7/site-packages/tensorflow/python/training/supervisor.py", line 990, in run_loop████████████▍                  | 24/51 [00:00<?, ?b/s]
    self._sv.global_step])
  File "/usr/local/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 778, in run  47%|████████████████▍                  | 24/51 [00:00<?, ?b/s]
    run_metadata_ptr)
  File "/usr/local/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 982, in _run 47%|████████████████▍                  | 24/51 [00:00<?, ?b/s]
    feed_dict_string, options, run_metadata)
  File "/usr/local/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1032, in _do_run|████████████████▍                  | 24/51 [00:00<?, ?b/s]
    target_list, options, run_metadata)
  File "/usr/local/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1052, in _do_call████████████████▍                  | 24/51 [00:00<?, ?b/s]
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Infinity in summary histogram for: gpu_0/HistogramSummary████▍                  | 24/51 [00:00<?, ?b/s]
	 [[Node: gpu_0/HistogramSummary = HistogramSummary[T=DT_FLOAT, _device="/job:localhost/replica:0/task:0/cpu:0"](gpu_0/HistogramSummary/tag, gpu_0/ctc)]]
train:  47%|████████████████▍                  | 24/51 [00:00<?, ?b/s]
Caused by op u'gpu_0/HistogramSummary', defined at:
  File "train.py", line 48, in <module>
    tf.sg_train(lr=0.0001, loss=get_loss(input=inputs, target=labels, seq_len=seq_len),
  File "/usr/local/lib/python2.7/site-packages/sugartensor/sg_main.py", line 592, in wrapper
    res.append(func(opt * tf.sg_opt(gpu_index=i)))
  File "train.py", line 43, in get_loss
    return logit.sg_ctc(target=opt.target[opt.gpu_index], seq_len=opt.seq_len[opt.gpu_index])
  File "/usr/local/lib/python2.7/site-packages/sugartensor/sg_main.py", line 170, in wrapper
    out = func(tensor, tf.sg_opt(kwargs))
  File "/usr/local/lib/python2.7/site-packages/sugartensor/sg_loss.py", line 230, in sg_ctc
    tf.sg_summary_loss(out, name=opt.name)
  File "/usr/local/lib/python2.7/site-packages/sugartensor/sg_logging.py", line 36, in sg_summary_loss
    _histogram(name + '-h', tensor)
  File "/usr/local/lib/python2.7/site-packages/sugartensor/sg_logging.py", line 176, in _histogram
    val = gen_logging_ops._histogram_summary(name, tensor)
  File "/usr/local/lib/python2.7/site-packages/tensorflow/python/ops/gen_logging_ops.py", line 139, in _histogram_summary
    name=name)
  File "/usr/local/lib/python2.7/site-packages/tensorflow/python/framework/op_def_library.py", line 768, in apply_op
    op_def=op_def)
  File "/usr/local/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 2336, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "/usr/local/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 1228, in __init__
    self._traceback = _extract_stack()

InvalidArgumentError

 (see above for traceback): Infinity in summary histogram for: gpu_0/HistogramSummary
	 [[Node: gpu_0/HistogramSummary = HistogramSummary[T=DT_FLOAT, _device="/job:localhost/replica:0/task:0/cpu:0"](gpu_0/HistogramSummary/tag, gpu_0/ctc)]]

**Comment by Noah-Franks** [comment]
Reinstalling all of the dependencies gets me this set of error messages

> Training started from epoch[000]-step[0].
/usr/local/lib/python2.7/site-packages/sugartensor/sg_train.py:333: RuntimeWarning: divide by zero encountered in remainder
  start_step = sess.run(tf.sg_global_step()) % opt.ep_size
I 0523:12:40:16.487:sg_train.py:301] 	Epoch[000:gs=0] - loss = NA
I 0523:12:40:16.489:sg_train.py:301] 	Epoch[001:gs=0] - loss = NA
I 0523:12:40:16.491:sg_train.py:301] 	Epoch[002:gs=0] - loss = NA
I 0523:12:40:16.493:sg_train.py:301] 	Epoch[003:gs=0] - loss = NA
I 0523:12:40:16.494:sg_train.py:301] 	Epoch[004:gs=0] - loss = NA
I 0523:12:40:16.496:sg_train.py:301] 	Epoch[005:gs=0] - loss = NA
I 0523:12:40:16.498:sg_train.py:301] 	Epoch[006:gs=0] - loss = NA
I 0523:12:40:16.500:sg_train.py:301] 	Epoch[007:gs=0] - loss = NA
I 0523:12:40:16.502:sg_train.py:301] 	Epoch[008:gs=0] - loss = NA
I 0523:12:40:16.503:sg_train.py:301] 	Epoch[009:gs=0] - loss = NA
I 0523:12:40:16.505:sg_train.py:301] 	Epoch[010:gs=0] - loss = NA

**Comment by rachel-bousfield** [comment]
I didn't mean to close this

**Comment by rachel-bousfield** [comment]
I found the issue. This project does not support the GSM encoding for .wav files. Converting my corpora to pcm_s16le did the trick.

**Comment by sevenseablue** [comment]
@Noah-Franks , i don't know anything about .wav encoding, can you explain it more details.

**Comment by cdyangbo** [comment]
when add a batch_normalization layer after the rnn layer ,'No valid path‘  warning appear. And replace  the bn layer with dropout layer ,everything is ok.

**Comment by f-gibellini** [comment]
Hi, I still have the problem also if all WAV files are now PCM encoded... any ideas?

**Comment by dizzyname** [comment]
@cdyangbo are you create a model by your self or just modify model.py from  buriburi ?
Because buriburi's model not use rnn layer.

**Comment by dizzyname** [comment]
@f-gibellini have you found the solution ?
