### ISSUE TITLE
Implementing a language model

### ISSUE THREAD

**Issue by lightnarcissus** [buriburisuri/speech-to-text-wavenet#83]
Does anyone have any recommendations on how one would go about training the trained model with a language model to move the output closer to the ground truth?

**Comment by ghost** [comment]
Any  light on this issue @buriburisuri

**Comment by MorganGellert** [comment]
Baidu's [DeepSpeech paper](https://arxiv.org/abs/1412.5567) trained a simple n-gram language model and used a weighted sum of the log probabilities and word count to combine the two models. The two were trained separately but the n-gram is much simpler and could be trained on many more utterances than the neural net.

**Comment by lightnarcissus** [comment]
@MorganGellert  Thank you!
